name: CI

on:
  push:
    branches: [ "**" ] # Trigger on pushes to all branches
  pull_request:
    branches: [ "**" ] # Also trigger on pull requests to all branches

permissions:
  contents: read

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Test against the minimum supported Python version and the latest stable version
        python-version: ['3.9', '3.12']

    steps:
      - uses: actions/checkout@v4

      - name: astral-sh/setup-uv
        uses: astral-sh/setup-uv@v5.3.1
        with:
          python-version: 3.9

      - name: Run Ruff linting
        run: |
          uvx ruff check

      - name: Run Pyright
        run: |
          uv run pyright src/

      - name: Run tests
        run: |
          uv run pytest tests/

      - name: Build package
        run: |
          uv build